# Generated by Django 3.0.5 on 2020-04-17 23:10

from django.db import migrations, models
import django.db.models.deletion
import django_thumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoset',
            name='itm_Fk_Item_id',
            field=models.ForeignKey(blank=True, help_text='Artikel waarbij deze foto hoort', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Item', verbose_name='Bij artikel'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=django_thumbs.fields.ImageThumbsField(blank=True, max_length=250, null=True, sizes=({'code': 'thumb', 'resize': 'crop', 'wxh': '69x100'}, {'code': 'galry', 'resize': 'crop', 'wxh': '400x580'}, {'code': 'detail', 'wxh': '552x800'}), upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='itm_Is_Frontpage',
            field=models.BooleanField(blank=True, default=True, verbose_name='Featured'),
        ),
    ]
