# Generated by Django 3.0.5 on 2020-04-23 12:48

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200417_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tekst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tks_Title', models.CharField(max_length=85, unique=True)),
                ('tks_Name_Long', models.TextField(blank=True, null=True)),
                ('tks_TheText', models.TextField(blank=True, null=True)),
                ('tks_Slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('tks_Title',))),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'teksten',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=core.fields.ImageThumbsField(blank=True, max_length=250, null=True, sizes=({'code': 'thumb', 'resize': 'crop', 'wxh': '69x100'}, {'code': 'galry', 'resize': 'crop', 'wxh': '400x580'}, {'code': 'detail', 'wxh': '552x800'}), upload_to=''),
        ),
        migrations.CreateModel(
            name='TextGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgn_Title', models.CharField(max_length=85, unique=True)),
                ('tgn_Name_Long', models.TextField(blank=True, null=True)),
                ('tgn_Slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('gnr_Title',))),
                ('lft', models.PositiveIntegerField(default=0)),
                ('rght', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=0)),
                ('tree_id', models.PositiveIntegerField(default=0)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.TextGenre')),
            ],
            options={
                'verbose_name_plural': 'genres',
            },
        ),
        migrations.CreateModel(
            name='ImageGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ign_Title', models.CharField(max_length=85, unique=True)),
                ('ign_Name_Long', models.TextField(blank=True, null=True)),
                ('ign_Slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('gnr_Title',))),
                ('lft', models.PositiveIntegerField(default=0)),
                ('rght', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=0)),
                ('tree_id', models.PositiveIntegerField(default=0)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.ImageGenre')),
            ],
            options={
                'verbose_name_plural': 'genres',
            },
        ),
    ]
