# Generated by Django 3.0.5 on 2020-05-04 22:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200423_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csn_Title', models.CharField(blank=True, default='', max_length=140, verbose_name='Title')),
                ('csn_CardTextUser', ckeditor.fields.RichTextField(blank=True, default='', help_text='Type hier de tekst die u wilt verzenden', verbose_name='UserText')),
                ('csn_ResipientNm', models.CharField(blank=True, default='', help_text='Optioneel', max_length=85, verbose_name='Ontvanger naam')),
                ('csn_SenderNm', models.CharField(blank=True, default='', help_text='Omdat die vaak vergeten wordt!', max_length=85, verbose_name='Afzender naam')),
                ('csn_ResipientChannel', models.CharField(blank=True, choices=[('E', 'E-Mail'), ('W', 'WhatsApp')], help_text='Via E-mail of via WhatsApp', max_length=1, null=True, verbose_name='Ontvanger kanaal')),
                ('csn_ResipChanNr', models.CharField(blank=True, default='', help_text='E-mail address of WhatsApp nummer', max_length=85, verbose_name='Ontvanger kanaal nummer')),
                ('csn_CardImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
    ]
