# Generated by Django 3.0.5 on 2020-05-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cardsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tekst',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tekst',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='tekst',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='tekst',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='cardsession',
            name='csn_CardTekst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tekst'),
        ),
    ]
