# Generated by Django 3.0.5 on 2020-11-22 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20200505_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='tekst',
            name='tks_Genres',
            field=models.ManyToManyField(to='core.TextGenre'),
        ),
        migrations.AlterField(
            model_name='cardsession',
            name='csn_CardTekst',
            field=models.ForeignKey(blank=True, help_text='Kies een standaard tekst die u eventueel kunt aanvullen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardTekst', to='core.Tekst', verbose_name='Standaard tekst'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prf_bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('prf_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ontvanger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ont_Naam', models.CharField(default='', max_length=125, verbose_name='Ontvanger naam')),
                ('ont_Email', models.CharField(blank=True, default='', max_length=125, verbose_name='E-mail')),
                ('ont_Mobiel', models.CharField(blank=True, default='', max_length=12, verbose_name='Mobile nr')),
                ('ont_User', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Profile', verbose_name='Bij Gebruiker')),
            ],
        ),
    ]
