# Generated by Django 3.0.5 on 2020-11-22 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201122_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Afbeelding', 'verbose_name_plural': 'Afbeeldingen'},
        ),
        migrations.AlterField(
            model_name='ontvanger',
            name='ont_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Profile', verbose_name='Bij Gebruiker'),
        ),
    ]
