# Generated by Django 3.0.5 on 2020-11-22 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201122_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsession',
            name='csn_ResipChanNr',
        ),
        migrations.RemoveField(
            model_name='cardsession',
            name='csn_ResipientNm',
        ),
        migrations.AddField(
            model_name='cardsession',
            name='csn_TheResipient',
            field=models.ForeignKey(blank=True, help_text='Kies een ontvanger', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Ontvanger', verbose_name='Ontvangers'),
        ),
    ]
