# Generated by Django 3.0.5 on 2020-11-23 00:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201122_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsession',
            name='cns_User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Profile', verbose_name='Gebruiker'),
        ),
        migrations.AlterField(
            model_name='cardsession',
            name='csn_CardTextUser',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Type hier de tekst die u wilt verzenden (u kunt ook een tekst kiezen en die hier aanpassen)', verbose_name='UserText'),
        ),
    ]
