# Generated by Django 3.0.5 on 2020-11-23 01:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201123_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tekst',
            name='tks_TheText',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
