# Generated by Django 3.0.5 on 2020-11-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201123_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prf_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='prf_Email',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='profile',
            name='prf_Mobiel',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Mobile nr'),
        ),
        migrations.AddField(
            model_name='profile',
            name='prf_Naam',
            field=models.CharField(default='Jan Jansen', help_text='Omdat die vaak vergeten wordt!', max_length=125, verbose_name='Afzender naam'),
        ),
        migrations.AddField(
            model_name='tekst',
            name='tks_Categories',
            field=models.ManyToManyField(to='core.Category'),
        ),
    ]
