# Generated by Django 3.0.5 on 2020-12-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201127_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsession',
            name='csn_DatTijdVerzonden',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cardsession',
            name='csn_ResipientChannel',
            field=models.CharField(blank=True, choices=[('E', 'E-Mail'), ('W', 'WhatsApp')], help_text='Via E-mail, Facebook, Sms of via WhatsApp', max_length=1, null=True, verbose_name='Ontvanger kanaal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prf_Naam',
            field=models.CharField(default='Jan Jansen', max_length=125, verbose_name='Default Afzender naam'),
        ),
    ]
