# Generated by Django 4.0.8 on 2023-03-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_prf_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prf_ActiveChat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Active chat'),
        ),
    ]
