# Generated by Django 3.0.5 on 2021-08-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_prf_profileimg'),
        ('chatApp', '0003_message_msg_chatgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='cht_Contacts',
        ),
        migrations.AddField(
            model_name='chat',
            name='Contacts',
            field=models.ManyToManyField(related_name='chats', related_query_name='chat', to='core.Profile'),
        ),
    ]
